---
title: "Pilot Analyses--Cross Domain Discounting"
author: "JC"
date: "4.10.20"
output:
  html_document: default
  code_folding: "hide"
---
#Cross-Domain Discounting Project (31 YAs)

```{r setup, warning=FALSE, message=FALSE}
rm(list=ls())

# Packages
library(lme4); library(knitr); library(kableExtra); library(RColorBrewer); library(tidyverse);
source("summarySEwithin2.R")

#Create data directories
coged.wm.path<-"~/Box Sync/CCPLab_Aging_Studies/Multi-Domain-Discounting/Data/WM-Cog-ED/coged_wm_data.csv"
coged.speech.path<-"~/Box Sync/CCPLab_Aging_Studies/Multi-Domain-Discounting/Data/Speech-Cog-ED/coged_speech_data.csv"
NASA.wm.path <- "~/Box Sync/CCPLab_Aging_Studies/Multi-Domain-Discounting/Data/Indvidual-Diff-Qs/MDD_NASA_WM.csv"
NASA.speech.path <- "~/Box Sync/CCPLab_Aging_Studies/Multi-Domain-Discounting/Data/Indvidual-Diff-Qs/MDD_NASA_Speech.csv"
NCS.path <- "~/Box Sync/CCPLab_Aging_Studies/Multi-Domain-Discounting/Data/Indvidual-Diff-Qs/MDD_NCS.csv"
Post.coged.wm.path <- "~/Box Sync/CCPLab_Aging_Studies/Multi-Domain-Discounting/Data/Indvidual-Diff-Qs/MDD_Post_CogED_WM.csv"
Post.coged.speech.path <- "~/Box Sync/CCPLab_Aging_Studies/Multi-Domain-Discounting/Data/Indvidual-Diff-Qs/MDD_Post_CogED_Speech.csv"

#Make data frames for Cog-ED and NASA TLX 
coged.wm <- read.csv(coged.wm.path, header = T)
coged.speech <- read.csv(coged.speech.path, header = T)
NASA.wm <- read.csv(NASA.wm.path, header = T)
NASA.speech <- read.csv(NASA.speech.path, header = T)
NCS <- read.csv(NCS.path, header = T)
Post.coged.wm <- read.csv(Post.coged.wm.path, header = T)
Post.coged.speech <- read.csv(Post.coged.speech.path, header = T)
```

```{r SV_CogED, warning=F, message=F}
#clean data frame with Cog-ED SV estimates and join data across both domains (i.e., WM, speech)
d.coged.wm <- coged.wm %>%
  group_by(subID, task) %>%
  dplyr::summarise(meanSV = mean(SV)) %>%
  mutate(Domain = "WM", 
         DomainCode = 0,
         taskCode = factor(task, levels=c(1,2,3), labels=c(-1,0,1)),
         task = factor(task, levels=c(1,2,3), labels=c("Red","Blue","Purple")))

d.coged.speech <- coged.speech %>%
  group_by(subID, task) %>%
  dplyr::summarise(meanSV = mean(SV)) %>%
  mutate(Domain = "Speech",
         DomainCode = 1,
          taskCode = factor(task, levels=c(1,2,3), labels=c(-1,0,1)),
          task = factor(task, levels=c(1,2,3), labels=c("Red","Blue","Purple")))

coged.merged <- rbind(d.coged.wm, d.coged.speech)

#testing for differences across task (WM, speech) & condition (red, blue, purple)
m.SV <- lmer(data = coged.merged, meanSV ~ taskCode*DomainCode + (1 | subID))
summary(m.SV)

#testing for differences across domain for each load level of the task
#Red Task (2-Back, -4SNR)
t.test(x = subset(coged.merged, Domain=="WM" & task=="Red")$meanSV,
       y = subset(coged.merged, Domain=="Speech" & task =="Red")$meanSV,
       paired = TRUE)
#Blue Task (3-Back, -8SNR)
t.test(x = subset(coged.merged, Domain=="WM" & task=="Blue")$meanSV,
       y = subset(coged.merged, Domain=="Speech" & task =="Blue")$meanSV,
       paired = TRUE)
#Purple Task (4-Back, -12SNR)
t.test(x = subset(coged.merged, Domain=="WM" & task=="Purple")$meanSV,
       y = subset(coged.merged, Domain=="Speech" & task =="Purple")$meanSV,
       paired = TRUE)
```

##Cognitive Effort Discounting
###Working Memory (Black = 1-back, Red = 2-Back, Blue = 3-back, Purple = 4-back)
###Speech (Black = 0 SNR, Red = -4 SNR, Blue = -8 SNR, Purple = -12 SNR)

``` {r CogED_Plot, warning = F, message = F}
CogED_sum <- summarySEwithin2(coged.merged, measurevar = "meanSV", withinvars = c("task", "Domain"), idvar = "subID")

#Plotting SV across both WM and speech domains
p.1 <- ggplot(CogED_sum, aes(x=task, y=meanSV)) + 
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_errorbar(position=position_dodge(width=0.9), aes(ymin=meanSV-ci, ymax=meanSV+ci), width=.2) +  
  coord_cartesian(ylim=c(0,1)) +
  xlab("Task") + ylab("Subjective Value") + ggtitle("Cross-Domain Cognitive Effort Discounting") + 
  facet_grid(.~ Domain)
p.1

p.2 <- ggplot(CogED_sum, aes(x=task, y=meanSV)) + 
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_errorbar(position=position_dodge(width=0.9), aes(ymin=meanSV-ci, ymax=meanSV+ci), width=.2) +  
   geom_point(data = coged.merged, aes(x=task, y=meanSV, group=subID),
             stat="identity", alpha=0.5) +
  geom_line(data = coged.merged, aes(x=task, y=meanSV, group=subID, colour = factor(subID)), alpha = .5) +
  coord_cartesian(ylim=c(0,1)) +
  xlab("Task") + ylab("Subjective Value") +
  facet_grid(.~ Domain)
p.CogED <- p.2 + guides(colour=FALSE) 
p.CogED

#Correlating Average SV (within-subj) across domains
average.SV <- coged.merged %>%
  group_by(subID, Domain) %>%
  dplyr::summarise(SV_avg = mean(meanSV)) %>%
  pivot_wider(values_from = "SV_avg", names_from = "Domain")

p.3 <- ggplot(average.SV, aes(Speech, WM)) +
   theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  geom_point() + geom_smooth(method=lm) +ggtitle("Average SV Estimates Across WM & Speech Domains")
p.3
cor(average.SV$Speech, average.SV$WM)
```

##Self-Report Questionnaires
###NASA TLX (administered after each run of the familiarization tasks)

``` {r NASA, warning = F, message = F}
#cleaning up data structures from REDCap
NASA.wm.clean <- NASA.wm %>% select( -"nasawm_complete") %>%
  pivot_longer(names_to = "condition", values_to = "rating", -record_id) %>%
  separate(col = condition, into=c("Task","Characteristic"), sep = "_") %>%
  pivot_wider(values_from = rating, names_from = Characteristic) %>%
  rename(mental_demand = mdemand, 
         phsyical_demand = pdemand, 
         temporal_demand = tdemand) %>%
  mutate(Domain = "WM")

NASA.speech.clean <- NASA.speech %>% select( -"nasaspeech_complete") %>%
  pivot_longer(names_to = "condition", values_to = "rating", -record_id) %>%
  separate(col = condition, into=c("Task","Characteristic"), sep = "_") %>%
  pivot_wider(values_from = rating, names_from = Characteristic) %>%
  rename(mental_demand = mdemand, 
         phsyical_demand = pdemand, 
         temporal_demand = tdemand) %>%
  mutate(Domain = "Speech")

NASA.merged <- rbind(NASA.wm.clean, NASA.speech.clean)

#Mental Demand Ratings
NASA.m.demand <- NASA.merged %>% select(record_id, Task, Domain, mental_demand) %>%
  group_by(record_id, Task, Domain) %>%
  dplyr::summarise(mean.m.demand = mean(mental_demand))
NASA_mdemand_sum <- summarySEwithin2(NASA.m.demand, measurevar = "mean.m.demand", withinvars = c("Task", "Domain"), idvar = "record_id")
NASA_mdemand_sum$Task <- factor(NASA_mdemand_sum$Task, levels = c("black", "red", "blue", "purple"), labels = c("black", "red", "blue", "purple"))

p.m.demand <- ggplot(NASA_mdemand_sum, aes(x=Task, y=mean.m.demand)) + 
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_errorbar(position=position_dodge(width=0.9), aes(ymin=mean.m.demand-ci, ymax=mean.m.demand+ci), width=.2) +  
  xlab("Task") + ylab("Mental Demand") + ggtitle("Self-Reported Mental Demand") + 
  facet_grid(.~ Domain)
p.m.demand

#Effort Ratings
NASA.effort <- NASA.merged %>% select(record_id, Task, Domain, effort) %>%
  group_by(record_id, Task, Domain) %>%
  dplyr::summarise(mean.effort = mean(effort))
NASA_effort_sum <- summarySEwithin2(NASA.effort, measurevar = "mean.effort", withinvars = c("Task", "Domain"), idvar = "record_id")
NASA_effort_sum$Task <- factor(NASA_effort_sum$Task, levels = c("black", "red", "blue", "purple"), labels = c("black", "red", "blue", "purple"))

p.effort <- ggplot(NASA_effort_sum, aes(x=Task, y=mean.effort)) + 
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_errorbar(position=position_dodge(width=0.9), aes(ymin=mean.effort-ci, ymax=mean.effort+ci), width=.2) +  
  xlab("Task") + ylab("Effort") + ggtitle("Self-Reported Effort") + 
  facet_grid(.~ Domain)
p.effort

#Frustration Ratings
NASA.frust <- NASA.merged %>% select(record_id, Task, Domain, frustration) %>%
  group_by(record_id, Task, Domain) %>%
  dplyr::summarise(mean.frust = mean(frustration))
NASA_frust_sum <- summarySEwithin2(NASA.frust, measurevar = "mean.frust", withinvars = c("Task", "Domain"), idvar = "record_id")
NASA_frust_sum$Task <- factor(NASA_frust_sum$Task, levels = c("black", "red", "blue", "purple"), labels = c("black", "red", "blue", "purple"))

p.frust <- ggplot(NASA_frust_sum, aes(x=Task, y=mean.frust)) + 
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_errorbar(position=position_dodge(width=0.9), aes(ymin=mean.frust-ci, ymax=mean.frust+ci), width=.2) +  
  xlab("Task") + ylab("Frustration") + ggtitle("Self-Reported Frustration") + 
  facet_grid(.~ Domain)
p.frust

#Correlating Average NASA TLX Ratings (within-subj) across domains
average.NASA <- NASA.merged %>%
  pivot_longer(names_to = "Characteristic", values_to = "rating", -c(record_id, Task, Domain)) %>%
  filter(Characteristic == c("mental_demand", "effort", "frustration")) %>%
  group_by(record_id, Characteristic, Domain) %>%
  dplyr::summarise(rating_avg = mean(rating, na.rm = T))  %>%
  pivot_wider(values_from = "rating_avg", names_from = "Domain")

p.NASA <- ggplot(average.NASA, aes(Speech, WM)) +
   theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  geom_point() + geom_smooth(method=lm) +ggtitle("NASA TLX Ratings Across WM & Speech Domains") +
    facet_grid(.~ Characteristic)
p.NASA

##Correlation Values
#Effort
NASA.effort.cor <- average.NASA %>% filter(Characteristic =="effort")
cor(NASA.effort.cor$Speech, NASA.effort.cor$WM)

#Frustration
NASA.frust.cor <- average.NASA %>% filter(Characteristic =="frustration")
cor(NASA.frust.cor$Speech, NASA.frust.cor$WM)

#Mental Demand
NASA.demand.cor <- average.NASA %>% filter(Characteristic =="mental_demand")
cor(NASA.demand.cor$Speech, NASA.demand.cor$WM)
```

###Need for Cognition
``` {r NCS, warning = F, message =  F}
NCS.clean <- NCS %>% select( -"ncs_complete") %>%
  mutate(NCS.score = rowSums(.[2:19]))
```

###Post-Task Questionnaires
####Cog-ED

``` {r PostTask, warning = F, message = F}
#cleaning up data structures from REDCap
WM.coged.clean <- Post.coged.wm %>% select( -c("posttaskcoged_wm_complete", "coged_hardchoice", "coged_easychoice")) %>%
  pivot_longer(names_to = "condition", values_to = "rating", -record_id) %>%
  separate(col = condition, into = c(NA,"Characteristic"), sep = "_") %>%
  mutate(Domain = "WM")

Speech.coged.clean <- Post.coged.speech %>% select( -c("posttaskcoged_speech_complete", "coged_hardchoice_speech", "coged_easychoice_speech")) %>%
  pivot_longer(names_to = "condition", values_to = "rating", -record_id) %>%
  separate(col = condition, into = c(NA,"Characteristic"), sep = "_") %>%
  mutate(Domain = "Speech")

PostTask.coged.merged <- rbind(WM.coged.clean, Speech.coged.clean)

#Post-Task Cog-ED Ratings
PT.coged.sum <- summarySEwithin2(PostTask.coged.merged, measurevar = "rating", withinvars = c("Characteristic", "Domain"), idvar = "record_id")
p.PT.coged <- ggplot(PT.coged.sum, aes(x=Domain, y=rating)) + 
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_errorbar(position=position_dodge(width=0.9), aes(ymin=rating-ci, ymax=rating+ci), width=.2) +  
  xlab("Task") + ylab("Rating") +
   facet_grid(.~ Characteristic)
p.PT.coged
```

